/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package org.sixlab.rename;

import java.io.File;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 * 
 * @author __USER__
 */
public class MainFrame extends javax.swing.JFrame
{
	
	/** Creates new form MainFrame */
	public MainFrame()
	{
		initComponents();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents()
	{
		
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jButton4 = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6587\u4ef6\u540d\u6570\u5b57\u8f6c\u6362");
		setLocationByPlatform(true);
		
		jButton1.setText("\u9009\u62e9\u8def\u5f84");
		jButton1.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton1ActionPerformed(evt);
			}
		});
		
		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton2ActionPerformed(evt);
			}
		});
		
		jButton3.setText("\u9000\u51fa");
		jButton3.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton3ActionPerformed(evt);
			}
		});
		
		jButton4.setText("\u91cd\u547d\u540d");
		jButton4.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				jButton4ActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(99, 99, 99)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		243,
																		Short.MAX_VALUE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jButton1))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton2)
																.addGap(75, 75,
																		75)
																.addComponent(
																		jButton4)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		84,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton3)))
								.addGap(50, 50, 50)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(91, 91, 91)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jButton1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										85, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton3)
												.addComponent(jButton4))
								.addGap(47, 47, 47)));
		
		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)
	{
		char[][] theChars = { { '零', '0' }, { '一', '1' }, { '二', '2' },
				{ '三', '3' }, { '四', '4' }, { '五', '5' }, { '六', '6' },
				{ '七', '7' }, { '八', '8' }, { '九', '9' } };
		String path = jTextField1.getText();
		if (path == null | path.equals(""))
		{
			JOptionPane.showMessageDialog(null, "请输入路径");
			return;
		}
		File parentFile = new File(path);
		File[] theFiles = parentFile.listFiles();
		for (File file : theFiles)
		{
			String fullFilename = file.getName();
			String newName = fullFilename;
			// String filename = fullFilename.substring(0,
			// fullFilename.lastIndexOf("."));
			// String fileType = fullFilename.substring(fullFilename
			// .lastIndexOf("."));
			
			for (char[] cc : theChars)
			{
				newName = newName.replace(cc[0], cc[1]);
			}
			
			for (int i = 0; i < newName.length(); i++)
			{
				char thechar = newName.charAt(i);
				char charBefor = 'A';
				char charAfter = 'B';
				if (i != 0)
				{
					charBefor = newName.charAt(i - 1);
				}
				if (i != newName.length() - 1)
				{
					charAfter = newName.charAt(i + 1);
				}
				if (thechar == '百')
				{
					if (Character.isDigit(charAfter))
					{
						newName = newName.replace("百", "");
					} else
					{
						newName = newName.replace("百", "00");
					}
				}
				if (thechar == '十')
				{
					if (Character.isDigit(charBefor))
					{
						if (Character.isDigit(charAfter))
						{
							newName = newName.replace("十", "");
						} else
						{
							newName = newName.replace('十', '0');
						}
					} else
					{
						if (Character.isDigit(charAfter))
						{
							newName = newName.replace('十', '1');
						} else
						{
							newName = newName.replace("十", "10");
						}
					}
					
				}
			}
			
			String partPath = file.getAbsolutePath();
			newName = partPath.substring(0, partPath.lastIndexOf("\\")) + "\\"
					+ newName;
			file.renameTo(new File(newName));
		}
		
	}
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)
	{
		jTextField1.setText(null);
	}
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
	{
		System.exit(0);
	}
	
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
	{
		JFileChooser aChooser = new JFileChooser();
		aChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		int returnVal = aChooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION)
		{
			jTextField1.setText(aChooser.getSelectedFile().getPath());
		}
	}
	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[])
	{
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new MainFrame().setVisible(true);
			}
		});
	}
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton		jButton1;
	private javax.swing.JButton		jButton2;
	private javax.swing.JButton		jButton3;
	private javax.swing.JButton		jButton4;
	private javax.swing.JTextField	jTextField1;
	// End of variables declaration//GEN-END:variables
	
}